name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # run daily at midnight UTC

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Contribution Snake Graph
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=800080&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
      - name: Commit and Push generated snake files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update snake images [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: snake-images
          path: dist/
